name: Deploy to Render

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to Render and wait
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
        wait-for-success: true

    - name: Run tests
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: sonu-puthuk
        repo: contract-tests
        github_token: ${{ secrets.PAT_TEST_RUN }}
        workflow_file_name: contract-test.yml
        ref: main
        wait_interval: 10
        wait_workflow: true